name: Auto Bump Versions

on:
  pull_request:                                     
    types: [created, edited]

jobs:
  build:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/version')
    runs-on: ubuntu-latest

    steps:
    - name: Update version minor
      if: contains(github.event.comment.body, '/version minor')
      run: |
        ./version.sh -u -n
        echo "BUMP_TYPE=minor" >> $GITHUB_ENV

    - name: Update version major
      if: contains(github.event.comment.body, '/version major')
      run: |
        ./version.sh -u -m
        echo "BUMP_TYPE=major" >> $GITHUB_ENV

    - name: Update version patch
      if: contains(github.event.comment.body, '/version patch')
      run: |
        ./version.sh -u -p
        echo "BUMP_TYPE=patch" >> $GITHUB_ENV
        
